### ISSUE TITLE
'new' vs 'old' frontend code generation

### ISSUE THREAD

**Issue by GlennCeusters** [OpenModelica/OMPython#111]
Dear all,

When trying to run a modelica model with OMPython, I get the same error messages as I would in OpenModelica with "old frontend for code generation" enabled. Unfortunately I only got this model to work in OpenModelica with this option disables, i.e. in the new frontend.

Is there a workaround to this in OMPython? Or should I debug the model in OpenModelica using the old frontend?

Many thanks for the help!

Cheers,
/Glenn

**Comment by casella** [comment]
For the time being, the new frontend is the default only in OMEdit, with some user-friendly fallback options. In all other OpenModelica environments, you need to set the appropriate debug flag with `setCommandLineOption("-d=newInst")`

In all likelyhood, from v. 1.16.0 the new frontend will be switched on by default in all environments, so this will no longer be necessary.

**Comment by adeas31** [comment]
Note that the right command is `setCommandLineOptions("-d=newInst")`. See also https://openmodelica.org/forum/default-topic/2885-ompython-new-vs-old-frontend-code-generation

**Comment by casella** [comment]
Yeah, sorry for the typo 😄

**Comment by GlennCeusters** [comment]
when using a ModelicaSystem object, it automatically creates a new OMCSession? Even-though a session is already running (with the new frontend enabled). Like:

>>> from OMPython import OMCSessionZMQ
>>> omc = OMCSessionZMQ()
>>> model_path=omc.sendExpression("getInstallationDirectoryPath()") + "/share/doc/omc/testmodels/"
>>> from OMPython import ModelicaSystem
>>> mod=ModelicaSystem(model_path + "BouncingBall.mo","BouncingBall")

**Comment by JKRT** [comment]
> 
> 
> when using a ModelicaSystem object, it automatically creates a new OMCSession? Even-though a session is already running (with the new frontend enabled).

Hi! 

Thanks for reporting this issue, could you make a new issue with more details regarding your question! 

Cheers, 

John
