### ISSUE TITLE
ModelicaSystem object creates new OMCSession

### ISSUE THREAD

**Issue by GlennCeusters** [OpenModelica/OMPython#112]
Hi all,

The documentation implies that when creating a new ModelicaSystem object it uses the previously created OMCSession.

![image](https://user-images.githubusercontent.com/29844834/74102147-27264b80-4b41-11ea-8fc9-244a37c7a352.png)

However, when calling  ModelicaSystem it automatically creates a new OMCSession. Is this as intended? I need to setCommandLineOptions before creating the ModelicaSystem object. This could be done by creating an empty ModelicaSystem() and then sendExpression("..."), but then buildModel() gives

`AttributeError: 'ModelicaSystem' object has no attribute 'modelName'`

**Comment by arun3688** [comment]
@GlennCeusters OMCSessionZMQ () and ModelicaSystem() are two different classes, and hence it is intended behaviour to create a new OMCSession. You can do setCommandLineOptions something like this with ModelicaSystem

```
from OMPython import ModelicaSystem
mod=ModelicaSystem("BouncingBall.mo", "BouncingBall")
mod.sendExpression("setCommandLineOptions(.....)")
mod.buildModel()
```

**Comment by GlennCeusters** [comment]
@arun3688 , thanks for your reply. I'm asking how to setCommandLineOptions before calling mod=ModelicaSystem("mymodel.mo", "MyModel") because my model only works with the new frontend and so that calling ModelicaSystem("mymodel.mo", "MyModel") fails.

```
from OMPython import ModelicaSystem
mod = ModelicaSystem()
mod.sendExpression('setCommandLineOptions("-d=newInst")')
mod.sendExpression("loadFile(cd() + \"/mymodel.mo\")")
mod.buildModel() #fails
```

In any case, the documentation is misleading.

**Comment by arun3688** [comment]
@GlennCeusters you cannot do that with ModelicaSystem() constructor

**Comment by adeas31** [comment]
#113 fixed this issue. Thanks @arun3688

**Comment by GlennCeusters** [comment]
First off, thanks the merge. I'm still getting an error however:

> Notification: Automatically loaded package Modelica 3.2.3 due to uses annotation.
> Notification: Automatically loaded package Complex 3.2.3 due to uses annotation.
> Notification: Automatically loaded package ModelicaServices 3.2.3 due to uses annotation.
> Notification: Automatically loaded package Buildings 6.0.0 due to uses annotation.
> Warning: Requested package Modelica of version 3.2.2, but this package was already loaded with version 3.2.3. You might experience problems if these versions are incompatible.
> Notification: Automatically loaded package BuildingSystems 2.0.0-beta due to uses annotation.
> Warning: Requested package Modelica of version 3.2.2, but this package was already loaded with version 3.2.3. You might experience problems if these versions are incompatible.
> Notification: Skipped loading package NcDataReader2 (2.4.0) using MODELICAPATH C:/Users/BEGLCEU/AppData/Local/OpenModelica1.15.0-dev-64bit/lib/omlibrary (uses-annotation may be wrong).
> 
> Expected end of text, found 't'  (at char 400), (line:2, col:121)
> None

When using 

```
omc = OMCSessionZMQ()
omc.sendExpression('setCommandLineOptions("-d=newInst")')
omc.sendExpression("loadFile(cd() + \"/my_model.mo\")")
omc.sendExpression("checkModel(my_model)")
```
the model works fine (and can be simulated when using proper inputs).

Cheers,
/Glenn

**Comment by casella** [comment]
> In any case, the documentation is misleading.

Could you be more precise and provide a suggestion so as to how to improve it?
