### ISSUE TITLE
Loading dependencies in ModelicaSystem

### ISSUE THREAD

**Issue by peterscherpelz** [OpenModelica/OMPython#114]
I'm trying to load a custom package and model using ModelicaSystem. E.g. I have files in my current directory:
```
TestPackage/package.mo
TestPackage/BouncingBall.mo
```

And so in python I do:
```
from OMPython import ModelicaSystem
mod = ModelicaSystem(
    "TestPackage/BouncingBall.mo",
    "TestPackage.BouncingBall",
    ["Modelica", "TestPackage/package.mo"],
)
```

When I run this, I get an error:
```
$ python run_model.py 
2020-02-27 14:08:05,317 - OMPython - INFO - OMC Server is up and running at file:////tmp/openmodelica.pscherpelz.port.98675bd6718747a0a04dcb3a5fe45caf pid=39793
loadFile Error: Error: Failed to insert class BouncingBall within TestPackage;

 the available classes were:
```

But I noticed that in `OMPython/__init__.py`, dependencies (lines 745-757) are actually loaded after the main model. If I put those dependencies at the top of the `__loadingModel()` function, everything loads normally.

Is there a reason dependencies are loaded after the main file? Is there something else I'm missing about setup? Thanks!

**Comment by adeas31** [comment]
Seems like your model `BouncingBall` is part of package `TestPackage`. If this is the case you should call,

```python
from OMPython import ModelicaSystem
mod = ModelicaSystem(
    "TestPackage/package.mo",
    "TestPackage.BouncingBall",
    ["Modelica"],
)
```

**Comment by peterscherpelz** [comment]
That did it! I didn't realize that the "package.mo" in the first argument was the correct syntax, but it works :) Closing this issue.
