### ISSUE TITLE
Install OMPython offline

### ISSUE THREAD

**Issue by Knot83** [OpenModelica/OMPython#115]
Hello All,
is there anyway to install OMPython offline? 

Unfortunately my company firewall doesn't permit to download using` python -m pip install -U .`

This is the error I get:

Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x00000000049BBD30>: Failed to establish a new connection: [Errno 10061] No connection could be made because the target machine actively refused it',)': /simple/future/

I do appreciate your help.

Thanks.

**Comment by sjoelund** [comment]
Simply download the git repository as zip or using git, then follow the instructions for a local installation: https://github.com/OpenModelica/OMPython#windows

**Comment by Knot83** [comment]
Thanks to direct me in the troubleshooting. As you correctly said there were some missing dependencies.

Anyway it was not need to download the repository from git since I used what's in the standard installation path C:\OpenModelica1.14.1-64bit\share\omc\scripts\PythonInterface.

Now it works!

Best Regards!
