### ISSUE TITLE
ERROR - OMC Server is down. Please start it!

### ISSUE THREAD

**Issue by amirj1984** [OpenModelica/OMPython#116]
Hi, 
I am recently trying to use OMPython; when I type: 
omc = OMCSessionZMQ()
I receive the error:
2020-05-11 12:45:54,638 - OMPython - ERROR - OMC Server is down. Please start it! Log-file says:
'C:\Users\Ajode\OneDrive' is not recognized as an internal or external command,
operable program or batch file.

Traceback (most recent call last):

  File "<ipython-input-15-3789e6038940>", line 1, in <module>
    omc = OMCSessionZMQ()

  File "C:\Users\Ajode\anaconda3\lib\site-packages\OMPython\__init__.py", line 545, in __init__
    self._connect_to_omc(timeout)

  File "C:\Users\Ajode\anaconda3\lib\site-packages\OMPython\__init__.py", line 568, in _connect_to_omc
    raise Exception("OMC Server is down. Could not open file %s" % self._port_file)

Exception: OMC Server is down. Could not open file C:/Users/AJODE~1/AppData/Local/Temp/openmodelica.port.2d8c47fd8f894f80b8527460d863bd54

Would you please help me with it?

**Comment by arun3688** [comment]
@amirj1984 , Can you check whether OPENMODELICAHOME is set as environment variable.

variableName : OPENMODELICAHOME
variable Value : C:/OpenModelicaXXXX/build

**Comment by amirj1984** [comment]
Dear @arun3688 
Thank you very much for your reply. Could you please let me know how to set OPENMODELICAHOME as an environment variable? I search the term but did not find it in OM folder.

**Comment by arun3688** [comment]
@amirj1984 You should set it in the windows environment variable. Please following  the steps here 
https://www.architectryan.com/2018/08/31/how-to-change-environment-variables-on-windows-10/
You must make sure the Variable value : C:/OpenModelicaXXX/build, should point to where you have installed OpenModelica

**Comment by amirj1984** [comment]
@arun3688 Thanks! I just checked and it points to where the OM is installed.

**Comment by arun3688** [comment]
you mean "OPENMODELICAHOME" is already set in your windows environment variable

**Comment by amirj1984** [comment]
@arun3688 , I think so. Please see the attachment.

![aaa](https://user-images.githubusercontent.com/51123927/81564404-f94ae000-9397-11ea-8285-e1f2f94e338e.jpg)

**Comment by arun3688** [comment]
@amirj1984 Hi i now understant the problem is related to "onedrive"  path location,  I see that openModelica is installed to oneDrive, This has some know issue, Could you please install OpenModelica in some othere location possibly directly in C :/, Please make sure you uninstall the previous version

**Comment by amirj1984** [comment]
@arun3688 I have built some models in this OM. If I uninstall it, I would lose them. How can I save them?

**Comment by amirj1984** [comment]
@arun3688 second questions is related to the type of version. I have seen that it is suggested to download the nightly build version for this issue. Does this help?

**Comment by arun3688** [comment]
> @arun3688 I have built some models in this OM. If I uninstall it, I would lose them. How can I save them?

You can save them as normal modelica file example "test.mo" and then you can again run this model

**Comment by arun3688** [comment]
> @arun3688 second question is related to the type of version. I have seen that it is suggested to download the nightly build version for this issue. Does this help?

Yes nighly builds always have the latest fixes

**Comment by alkhwarizmi** [comment]
Hello,

I think the problem is that the code can't manage folder names with spaces.

I have done a patch that could fix this. Nothe the doulbe quotes around parameter {0}.
```
    def _set_omc_command(self, omc_path, args):
        #self._omc_command = "{0} {1}".format(omc_path, args)
        self._omc_command = '"{0}" {1}'.format(omc_path, args)
        return self._omc_command
```
Moreover, looking at the source code I found something that doesn't seem to be correct 
```
    def _start_omc_process(self):
        if sys.platform == 'win32':
            # omhome_bin = os.path.join(self.omhome, 'bin').replace("\\", "/") # Why this on Windows?
            omhome_bin = os.path.join(self.omhome, 'bin')
            my_env = os.environ.copy()
            my_env["PATH"] = omhome_bin + os.pathsep + my_env["PATH"]
            self._omc_process = subprocess.Popen(self._omc_command, shell=True, stdout=self._omc_log_file, stderr=self._omc_log_file, env=my_env)
        else:
            # Because we spawned a shell, and we need to be able to kill OMC, create a new process group for this
            self._omc_process = subprocess.Popen(self._omc_command, shell=True, stdout=self._omc_log_file, stderr=self._omc_log_file, preexec_fn=os.setsid)
        return self._omc_process
```
What's the purpose of replacing the escaped backslash with the slash character? This results in a at least in an ugly formatted path, if not actually wrong.

Let me know.

Sincerely,

**Comment by amirj1984** [comment]
@arun3688 I just downloaded OM and saved in C: ; However, in Python, I just typed:
import OMPython
from OMPython import OMCSessionZMQ
omc = OMCSessionZMQ()
and the error is different now:
Traceback (most recent call last):
  File "<ipython-input-4-3789e6038940>", line 1, in <module>
    omc = OMCSessionZMQ()
  File "C:\Users\Ajodeirikhoshbaf\anaconda3\lib\site-packages\OMPython\__init__.py", line 537, in __init__
    OMCSessionHelper.__init__(self)
  File "C:\Users\Ajodeirikhoshbaf\anaconda3\lib\site-packages\OMPython\__init__.py", line 117, in __init__
    raise ValueError("Cannot find OpenModelica executable, please install from openmodelica.org")
ValueError: Cannot find OpenModelica executable, please install from openmodelica.org

**Comment by amirj1984** [comment]
@alkhwarizmi Thank you for your advice; Please let me to go through the advice I've already received, if not answered, I will get back to you.

**Comment by alkhwarizmi** [comment]
Dear developers,

I see that the current source code is quite different from the version that gets installed by pip following the recommendations.

This is in contrast with the information users would get from the show command, which would be  identical (compare actual version string in the source code with the following message I received now on my PC). 
```
Someone>pip show ompython
Name: OMPython
Version: 3.1.2
Summary: OpenModelica-Python API Interface
Home-page: http://openmodelica.org/
Author: Anand Kalaiarasi Ganeson
Author-email: ganan642@student.liu.se
License: BSD, OSMC-PL 1.2, GPL (user's choice)
Location: c:\anaconda3\lib\site-packages
Requires: numpy, pyzmq, future, pyparsing
Required-by:
```

I would recommend to:

1. Update the distribution (as the current bug disqualifies it from being "stable");
2. If you don't update the distribution, provide instructions to install from the source code, instead.

Regarding this, I think I have successfully installed the current master branch with the following commands 
```
cd <path to your local copy of the OMPython git repository>
python -m pip install -U .
```
after having cloned the GitHub repository.

This seems to have fixed this error:
```
2020-05-11 17:14:22,847 - OMPython - INFO - OMC Server is up and running at file:///C:/Users/XXXXX~1/AppData/Local/Temp/openmodelica.port.a92dd0351a1c44518aa47046922567de pid=14960
```

Sincerely,

**Comment by arun3688** [comment]
@amirj1984 , It says omc is not found, Can you please change the "OPENMODELICAHOME" , environment variable value, to the new installed location

**Comment by amirj1984** [comment]
@arun3688 the variable value is at the installation location!

**Comment by arun3688** [comment]
@what is the installation location, can you please post it

**Comment by amirj1984** [comment]
@arun3688 Please find the attached files.
![aaa](https://user-images.githubusercontent.com/51123927/81582465-623e5200-93b0-11ea-81f0-908ac3900be6.png)
![bbb](https://user-images.githubusercontent.com/51123927/81582468-636f7f00-93b0-11ea-97b3-27de713d49c2.png)

**Comment by arun3688** [comment]
@can you restart your system and then do the following commands

>> from OMPython import OMCSessionZMQ
>> omc = OMCSessionZMQ()

**Comment by Ciobrelis** [comment]
Just simply install OpenModelica in OSDisk(C:) or any other Folder in your HD that is without any spaces in the name. You have "Program Files", which has space in the middle. This is the only reason why it doesn't work.

**Comment by amirj1984** [comment]
> @can you restart your system and then do the following commands
> 
> > > from OMPython import OMCSessionZMQ
> > > omc = OMCSessionZMQ()

2020-05-11 18:02:21,040 - OMPython - ERROR - OMC Server is down. Please start it! Log-file says:
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

Traceback (most recent call last):

  File "<ipython-input-3-3789e6038940>", line 1, in <module>
    omc = OMCSessionZMQ()

  File "C:\Users\Ajodeirikhoshbaf\anaconda3\lib\site-packages\OMPython\__init__.py", line 545, in __init__
    self._connect_to_omc(timeout)

  File "C:\Users\Ajodeirikhoshbaf\anaconda3\lib\site-packages\OMPython\__init__.py", line 568, in _connect_to_omc
    raise Exception("OMC Server is down. Could not open file %s" % self._port_file)

Exception: OMC Server is down. Could not open file C:/Users/AJODEI~1/AppData/Local/Temp/openmodelica.port.b190caba14904ed189e454712ea416f8

**Comment by arun3688** [comment]
@amirj1984  The Problem is related to spaces in the path, "c:/Program  Files", So just copy the OpenModelica1.16.0-dev-64bit, directly into the following path "C:/OpenModelica1.16.0-dev-64bit" and change path in the environment variable and restart your computer, that should fix the problem

**Comment by amirj1984** [comment]
@arun3688 thank you very much for helping with this regard. It's solved through changing the location of OM folder as suggested by @alkhwarizmi and @Ciobrelis .
