### ISSUE TITLE
buildModel() via sendExpression fails to build a model correctly built by OMEdit

### ISSUE THREAD

**Issue by alkhwarizmi** [OpenModelica/OMPython#118]
Dear all,

I have problems building a model with OMPython via sendExpression. The model is known to run if compiled with the OMEdit.
 
For details, including compiler outputs in the two cases, see https://trac.openmodelica.org/OpenModelica/ticket/5956

Sincerely,

**Comment by adeas31** [comment]
Reported as fixed in Trac.
