### ISSUE TITLE
How to modify a component's value within a redeclare statement via OMPython?

### ISSUE THREAD

**Issue by jnettels** [OpenModelica/OMPython#119]
Hello there!
To be clear, this is a question, not an issue. So please delete if this is inappropriate.

I asked this question on stackoverflow, with a complete working example and more explanation:
https://stackoverflow.com/questions/62168453

But the gist is: I would like to be able to replace the "sensitivity" in the example below via OMPython. Using omc.sendExpression() with setComponentModifierValue() allows me to edit ```component.value```, but not anything within a redeclare statement.
```
  model System "A system with a component"
    Component component(value = 200, redeclare SpecialSensor sensor(sensitivity = 10)) "Modified component";
  end System;
```
I would be grateful for any advice.

**Comment by adeas31** [comment]
https://www.openmodelica.org/forum/default-topic/3011-how-to-modify-a-component-s-value-within-a-redeclare-statement-via-cli#p10059

**Comment by jnettels** [comment]
Now you beat me to linking to your answer on openmodelica.org. I am closing this issue, since it is independent of OMPython.
