### ISSUE TITLE
Python 3.9 failure: 'xml.etree.ElementTree.Element' object has no attribute 'getchildren'

### ISSUE THREAD

**Issue by Midren** [OpenModelica/OMPython#135]
Next simple snippet is falling because of  changes in 3.9
```py
omc = OMCSessionZMQ()
model_path = omc.sendExpression('getInstallationDirectoryPath()') 
model = ModelicaSystem(model_path + "/share/doc/omc/testmodels/BouncingBall.mo","BouncingBall",["Modelica"])
```

**Comment by arun3688** [comment]
@Midren this issue is fixed with this commit https://github.com/OpenModelica/OMPython/commit/59ef1e3ea25ccc5b60496622b0415df36316d3c0, this change is not available via pip install i guess, So you should build OMPython from the source

**Comment by Midren** [comment]
@arun3688 I was using the latest version from pip. Thanks for the help!
