### ISSUE TITLE
can not change numberOfIntervals from Python script

### ISSUE THREAD

**Issue by Arinomo** [OpenModelica/OMPython#146]
Simulating a model by passing following argument:
`omc.sendExpression('simulate(stupidmodel, stopTime = 8.75, numberOfIntervals = 1000.0, outputFormat = "csv", variableFilter = ".*")')`

resulting in a successful simulation with a wrong numberofIntervals parameter
```
{'resultFile': 'R:/.../stupidmodel_res.csv',
 'simulationOptions': "startTime = 0.0, stopTime = 8.75, numberOfIntervals = 500, tolerance = 1e-06, method = 'dassl', fileNamePrefix = 'stupidmodel', options = '', outputFormat = 'csv', variableFilter = '.*', cflags = '', simflags = ''",
 'messages': 'LOG_SUCCESS       | info    | The initialization finished successfully without homotopy method.\nLOG_SUCCESS       | info    | The simulation finished successfully.\n',
 'timeFrontend': 0.1349161,
 'timeBackend': 0.0013348,
 'timeSimCode': 0.0004693,
 'timeTemplates': 0.0666831,
 'timeCompile': 5.4962187,
 'timeSimulation': 1.2424374,
 'timeTotal': 6.9476745}
```

it works for other parameters but not for the numberOfIntervals

=== Infos ==
Python 3.9.6
IPython 7.26.0

**Comment by Arinomo** [comment]
Solved. it only accept int and not float. My bad.

**Comment by Arinomo** [comment]
Hallo @casella ,

i know the ticket is invalid, but i would suggest an update to [https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/scripting_api.html] since there, under the simualte description, numberOfInterval is defined as Real and there are no warning when i pass float to numberOfInterval when using OMPython.

Cheers

**Comment by perost** [comment]
> Hallo @casella ,
> 
> i know the ticket is invalid, but i would suggest an update to [https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/scripting_api.html] since there, under the simualte description, numberOfInterval is defined as Real and there are no warning when i pass float to numberOfInterval when using OMPython.
> 
> Cheers

Fixed in OpenModelica/OpenModelica#7896. The scripting documentation in the user's guide is automatically generated from a ModelicaBuiltin package defined in the compiler, and for some reason `numberOfIntervals` was defined as a Real there while the rest of the compiler assumes it to be an Integer. That doesn't actually matter for `simulate` to work properly, but we should of course make sure the documentation is as accurate as possible.

**Comment by casella** [comment]
Thanks @perost, problem solved :)

**Comment by Arinomo** [comment]
@perost thanks for the update!

> That doesn't actually matter for `simulate` to work properly, but we should of course make sure the documentation is as accurate as possible.

Yeah, but i accidentally pass a Real number (1000.0) when using OMPython and the simulation was completed by reverting the `numberOfInterval` back to 500 with out and additional message. I was puzzeled to why OMPython reacted like it was and hench the ticket.
