### ISSUE TITLE
New release to pypi to support py3.9 and above

### ISSUE THREAD

**Issue by henloef** [OpenModelica/OMPython#150]
I am currently installing version 3.3.0 from pypi, but this version does not yet include a fix for https://docs.python.org/3.8/library/xml.etree.elementtree.html#xml.etree.ElementTree.Element.getchildren

This commit has fixed the issue https://github.com/OpenModelica/OMPython/commit/59ef1e3ea25ccc5b60496622b0415df36316d3c0

Is it possible to get a new release that includes this commit published to [pypi](https://pypi.org/project/OMPython/#history)?

**Comment by adeas31** [comment]
@arun3688 can you please publish a new version.

**Comment by adeas31** [comment]
A new release with the fix is available now.
