### ISSUE TITLE
can not simulate ModelicaSystem if the current working directory is changed

### ISSUE THREAD

**Issue by Arinomo** [OpenModelica/OMPython#156]
In following case ModelicaSystem user can not simulate the model because the exe-file was not found

```.py
from OMPython import ModelicaSystem
import os

mo = ModelicaSystem('foo.mo', 'foo')
os.chdir('./foo/bar')

mo.simulate()
```

resulting in an exception
```.py
Exception: Error: application file not generated yet
```

is it an intended behavior or a bug?

**Comment by adeas31** [comment]
Why do you want to change the directory before simulation? `ModelicaSystem` sets the working directory and then generates the files needed to run the simulation. The exception you are seeing is the intended behavior.

**Comment by Arinomo** [comment]
I was trying something on ipython console and change the worrking directory after instantiate ```ModelicaSysytem```. If it is the intended behaviour then its ok. Cheers
