### ISSUE TITLE
mod.getParameters("GAIN") issue and mod.setParameters("GAIN=2.0") issue

### ISSUE THREAD

**Issue by KAITO-FBX** [OpenModelica/OMPython#162]
Thank you for your great work and for dealing with this issue.

### Description
I am trying to access and set values of Parameters of a model or its simulation options.
As an example a mod.getParameter or getSimulationOptions() do produce a correct dictionary but
a targeted access to a specific parameters produces errors
 >>> mod.getSimulationOptions()
{'solver': 'dassl', 'stepSize': 0.02, 'tolerance': 1e-06, 'startTime': 0.0, 'stopTime': 10.0}
>>> mod.getSimulationOptions("solver")
's' is not in list
>>> mod.getSimulationOptions(["stepSize","tolerance"])
Error!!![['stepSize', 'tolerance']] does not exist.

The mod.setParameters() function also produces issues as follows
>>> mod.getParameters()  
{'secondOrder.D': 0.15, 'step.offset': 0.0, 'step.height': 1.0, 'integrator.y_start': 0.0, 'gain.k': None, 'secondOrder.initType': 1.0, 'integrator.initType': 3.0, 'integrator.k': 1.0, 'GAIN': 1.0, 'secondOrder.k': 1.0, 'secondOrder.y_start': 0.0, 'secondOrder.w': 10.0, 'secondOrder.yd_start': 0.0, 'integrator.use_reset': 0.0, 'integrator.use_set': 0.0, 'step.startTime': 1.0}
>>> mod.setParameters("GAIN=2")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: setParameters() takes 1 positional argument but 2 were given

A simulation can run and produce results which we can access !! specifically as follows:
>>> Y= mod.getSolutions("OUTPUT")
This produces a correct <class 'numpy.ndarray'> array with correct values.

 
### Steps to Reproduce
It seems that I have followed the documentation process.
The model test00.mo I have built is correctly behaving in OMEdit and with ONShell and 
OMPython except for this issue.

from OMPython import OMCSessionZMQ
omc = OMCSessionZMQ()
omc.sendExpression("getVersion()")
Local_Dir = omc.sendExpression("cd()")
from OMPython import ModelicaSystem
mod = ModelicaSystem(Local_Dir+"/test00.mo", "test00")
mod.simulate()
mod.getSolutions() 
mod.getSolutions(["T", "OUTPUT"]); ## filter the results 

### Expected Behavior
As documented

### Screenshots
No need

### Version and OS
OpenModelica 1.19.0~dev.beta2-7-g132048b
OMPython==3.4.0 on Python3.5 installed with pip
Debian GNU/Linux 9.13 (stretch)
Based on a the documentation OpenModelica User’s Guide, Release v1.20.0-dev-102-gd1c1c19430

**Comment by KAITO-FBX** [comment]
I have checked your code in def getParameters(self, names=None): 
...~ ... there is a test on the values of names without a space between the if and the test
        if(names==None):
            return self.paramlist
        elif(isinstance(names, str)):
            return [self.paramlist.get(names,"NotExist")]
        elif(isinstance(names, list)):
            return ([self.paramlist.get(x,"NotExist") for x in names])

Whereas on     def getSolutions(self, varList=None, resultfile=None): 
the space is nice. 

This might be the reason you have this issue.
Do you agree?

**Comment by KAITO-FBX** [comment]
Some investigations  on my side : 
-1- Apparently in the documentation it is possible to do this : mod.buildModel() Here is what I  have 
after this :+1: import OMPython as omp
#from OMPython import OMCSessionZMQ
#from OMPython import ModelicaSystem
Local_Dir=os.curdir
mod = omp.ModelicaSystem(Local_Dir+"/test00.mo", "test00",  ["Modelica"],useCorba=False)
I tried this : 
mod.buildModel()
----> AttributeError: 'ModelicaSystem' object has no attribute 'buildModel'

So I then tried this : 
>>> mod.requestApi("buildModel", mod.modelName)
('<<SOME PATH >>/test00', 'test00_init.xml')
>>> mod.requestApi("getErrorString")
'Warning: Requested package Modelica of version 4.0.0, but this package was already loaded with version 3.2.3. There are no conversion annotations for this version but 4.0.0 is newer than 3.2.3. There is a possibility that 3.2.3 remains backwards compatible, but it is not loaded so OpenModelica cannot verify this.\nNotification: Modelica requested package Complex of version 3.2.3. Complex 4.0.0 is used instead which states that it is fully compatible without conversion script needed.\nNotification: Modelica requested package ModelicaServices of version 3.2.3. ModelicaServices 4.0.0 is used instead which states that it is fully compatible without conversion script needed.\nWarning: Requested package Modelica of version 4.0.0, but this package was already loaded with version 3.2.3. There are no conversion annotations for this version but 4.0.0 is newer than 3.2.3. There is a possibility that 3.2.3 remains backwards compatible, but it is not loaded so OpenModelica cannot verify this.\nWarning: Assuming fixed start value for the following 2 variables:\n         secondOrder.yd:VARIABLE(start = secondOrder.yd_start fixed = true )  "Derivative of y" type: Real\n         secondOrder.y:VARIABLE(flow=false start = secondOrder.y_start fixed = true )  "Connector of Real output signal" type: Real\n'

**Comment by KAITO-FBX** [comment]
Sorry for so much comments  here is a test with python2.7 on a terminal : mod.getParameters("GAIN") works but not 

>>> mod = omp.ModelicaSystem("test00.mo","test00")
2022-05-25 09:27:39,226 - OMPython - INFO - OMC Server is up and running at file:////tmp/openmodelica.frederic.port.0ef28b4792414b368be0b2435e19e38e pid=6747
Notification: Automatically loaded package Modelica 4.0.0 due to uses annotation.
Notification: Automatically loaded package Complex 4.0.0 due to uses annotation.
Notification: Automatically loaded package ModelicaServices 4.0.0 due to uses annotation.

>>> mod.buildModel()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'ModelicaSystem' object has no attribute 'buildModel'

Regarding the issue : 
>>> mod.getParameters()
{'integrator.use_reset': 0.0, 'integrator.y_start': 0.0, 'secondOrder.w': 10.0, 'step.startTime': 1.0, 'secondOrder.y_start': 0.0, 'secondOrder.yd_start': 0.0, 'step.offset': 0.0, 'secondOrder.initType': 1.0, 'integrator.k': 1.0, 'GAIN': 1.0, 'step.height': 1.0, 'secondOrder.D': 0.15, 'secondOrder.k': 1.0, 'gain.k': None, 'integrator.initType': 3.0, 'integrator.use_set': 0.0}
>>> mod.getParameters("integrator.w")  <------------- This one is not working 
Error!!!['integrator.w'] does not exist.
>>> mod.getParameters("GAIN")   <-----------This one is working !! and not in python3.5
1.0

REMARK : These parameters are changeable 
>>> mod.getQuantities()[13]
{'aliasvariable': None, 'Name': 'integrator.k', 'Variability': 'parameter', 'Value': '1.0', 'alias': 'noAlias', 'Changeable': 'true', 'Description': 'Integrator gain'}
>>> mod.getQuantities()[11]
{'aliasvariable': None, 'Name': 'GAIN', 'Variability': 'parameter', 'Value': '1.0', 'alias': 'noAlias', 'Changeable': 'true', 'Description': None}

**Comment by arun3688** [comment]
@KAITO-FBX I could not reproduce the issue, I tested a simple example "BouncingBall.mo" see below

```
model BouncingBall
  parameter Real e = 0.7 "coefficient of restitution";
  parameter Real g = 9.81 "gravity acceleration";
  Real h(start = 1) "height of ball";
  Real v "velocity of ball";
  Boolean flying(start = true) "true, if ball is flying";
  Boolean impact;
  Real v_new;
equation
  impact = h <= 0.0;
  der(v) = if flying then -g else 0;
  der(h) = v;
  when {h <= 0.0 and v <= 0.0, impact} then
    v_new = if edge(impact) then -e * pre(v) else 0;
    flying = v_new > 0;
    reinit(v, v_new);
  end when;
end BouncingBall;
```

```
>>> from OMPython import ModelicaSystem
>>> omc = ModelicaSystem("BouncingBall.mo", "BouncingBall")
>>> omc = ModelicaSystem("C:/OPENMODELICAGIT/OpenModelica/OMSens/resource/BouncingBall.mo", "BouncingBall")
>>> omc.getParameters()
{'e': '0.7', 'g': '9.81'}
>>> omc.getParameters("e")
['0.7']
>>> omc.getSimulationOptions()
{'startTime': '0', 'stopTime': '1', 'stepSize': '0.002', 'tolerance': '1e-06', 'solver': 'dassl'}
>>> omc.getSimulationOptions("solver")
['dassl']
>>>
```

It would be good if you can attach your model `test00.mo`, to see whether i can reproduce the issue

**Comment by KAITO-FBX** [comment]
Thank you for your reply , please find following the model.
I also will test the bouncing ball demo.


model test00
extends Modelica.Icons.Example;
  parameter Real GAIN=1;
  Real OUTPUT;
  Real T;
  Modelica.Blocks.Continuous.SecondOrder secondOrder(D = 0.15, w = 10)  annotation(
    Placement(visible = true, transformation(origin = {30, 0}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Blocks.Continuous.Integrator integrator annotation(
    Placement(visible = true, transformation(origin = {64, 0}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Blocks.Math.Feedback feedback annotation(
    Placement(visible = true, transformation(origin = {-52, 0}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Blocks.Sources.Step step(startTime = 1)  annotation(
    Placement(visible = true, transformation(origin = {-82, 0}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
  Modelica.Blocks.Math.Gain gain(k = GAIN)  annotation(
    Placement(visible = true, transformation(origin = {-16, 0}, extent = {{-10, -10}, {10, 10}}, rotation = 0)));
equation
 OUTPUT = integrator.y;
 T=time;
  connect(step.y, feedback.u1) annotation(
    Line(points = {{-71, 0}, {-60, 0}}, color = {0, 0, 127}));
  connect(secondOrder.y, integrator.u) annotation(
    Line(points = {{41, 0}, {52, 0}}, color = {0, 0, 127}));
  connect(integrator.y, feedback.u2) annotation(
    Line(points = {{75, 0}, {88, 0}, {88, -40}, {-52, -40}, {-52, -8}}, color = {0, 0, 127}));
  connect(feedback.y, gain.u) annotation(
    Line(points = {{-43, 0}, {-29, 0}}, color = {0, 0, 127}));
  connect(gain.y, secondOrder.u) annotation(
    Line(points = {{-5, 0}, {17, 0}}, color = {0, 0, 127}));

annotation(
    uses(Modelica(version = "4.0.0")),
    experiment(StartTime = 0, StopTime = 10, Tolerance = 1e-6, Interval = 0.02));
end test00;

**Comment by arun3688** [comment]
@KAITO-FBX  I tested your model `test00.mo` and it works for me i could not reproduce the issue, see the below test 


```
(base) c:\test>python
Python 3.8.5 (default, Sep  3 2020, 21:29:08) [MSC v.1916 64 bit (AMD64)] :: Anaconda, Inc. on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from OMPython import ModelicaSystem
>>> omc = ModelicaSystem("test00.mo", "test00")
Notification: Automatically loaded package Modelica 4.0.0 due to uses annotation.
Notification: Automatically loaded package Complex 4.0.0 due to uses annotation.
Notification: Automatically loaded package ModelicaServices 4.0.0 due to uses annotation.

>>> omc.getParameters()
{'GAIN': '1.0', 'gain.k': None, 'integrator.k': '1.0', 'integrator.y_start': '0.0', 'secondOrder.D': '0.15', 'secondOrder.k': '1.0', 'secondOrder.w': '10.0', 'secondOrder.y_start': '0.0', 'secondOrder.yd_start': '0.0', 'step.height': '1.0', 'step.offset': '0.0', 'step.startTime': '1.0', 'integrator.initType': '3', 'secondOrder.initType': '1', 'integrator.use_reset': 'false', 'integrator.use_set': 'false'}
>>> omc.getParameters("secondOrder.D")
['0.15']
>>> omc.getParameters(["GAIN", "secondOrder.w"])
['1.0', '10.0']
>>> omc.getSimulationOptions()
{'startTime': '0', 'stopTime': '10', 'stepSize': '0.02', 'tolerance': '1e-06', 'solver': 'dassl'}
>>> omc.getSimulationOptions("solver")
['dassl']
>>> omc.getSimulationOptions(["solver", "tolerance"])
['dassl', '1e-06']
>>> omc.setParameters("GAIN=2")
>>> omc.getParameters("GAIN")
['2']
>>> 
```
We do not test much in `Python 2.XX versions`, I suggest you to `uninstall` the package and reinstall the OMPython

**Comment by KAITO-FBX** [comment]
Thank you very much I have noticed that you have used python with conda and with version 3.8 ... and my version was 3.5 ... so I will try with this as well (probably 3.9)
Thank you again for your help and will return to you asap

**Comment by KAITO-FBX** [comment]
Well done , Thank you very much.      It seems that my python install was corrupted.
So conda + python3.9 seems to work well with a reinstalled ompython and zmq package..

I sincerely hope that I this issue on my side didn't take too much of your time, sorry about that.
