### ISSUE TITLE
How to generate. fmu files using mod. convertMo2Fmu()

### ISSUE THREAD

**Issue by dephat** [OpenModelica/OMPython#167]
When I used OMPython to generate. fmu files from. mo files, only the fmutmp folder and some other files with suffixes were generated. It is obvious that there is a problem, but I am not sure where the problem lies. Below are screenshots of the code and generated files I used. I hope someone can help me. Thank

from OMPython import OMCSessionZMQ
omc = OMCSessionZMQ()
model_path=omc.sendExpression("getInstallationDirectoryPath()") + "/"
print(omc.sendExpression("getInstallationDirectoryPath()"))
from OMPython import ModelicaSystem
mod=ModelicaSystem(model_path + "Tank.mo","Tank")
ffmu = mod.convertMo2Fmu()

![image](https://github.com/OpenModelica/OMPython/assets/48836179/df05d72c-10dc-4d74-8949-9f4e07b10555)

tank1234.fmutmp is a folder, as shown in the following figure

![image](https://github.com/OpenModelica/OMPython/assets/48836179/c1cf2cab-104f-42a2-b7e0-9418db02907d)

**Comment by arun3688** [comment]
@casella sure i will try to look into this today

**Comment by arun3688** [comment]
@dephat I cannot reproduce the error and it works for me, see the below script 

```
>>> from OMPython import ModelicaSystem
>>> mod = ModelicaSystem()
>>> mod = ModelicaSystem("C:/OPENMODELICAGIT/OpenModelica/OMCompiler/Examples/BouncingBall.mo", "BouncingBall")
>>> mod.convertMo2Fmu()
'c:/OPENMODELICAGIT/OpenModelica/testsuite/openmodelica/dataReconciliation/BouncingBall.fmu'
```

Based on your script, I suggest that you put the absolute path of the `ModelicaModel (tank.mo)` and run the API and i hope this should solve the problem.

**Comment by dephat** [comment]
@arun3688 Sorry for not responding in a timely manner. As a student, I was preparing for the exam two weeks ago. I realized that the previous issue was that the omlibrary was not properly installed, and now there is a new error,Is this a missing environment variable that has not been configured?
![image](https://github.com/OpenModelica/OMPython/assets/48836179/b591cdbd-88e4-47ac-af4f-4fdbf5b138c7)

**Comment by arun3688** [comment]
Hello in the above code the API is wrong it should be mod.convertMo2Fmu()
regards
arun

**Comment by dephat** [comment]
@arun3688 thanks,for your help
