### ISSUE TITLE
fetch ipopt information from ModelicaSystem simulation

### ISSUE THREAD

**Issue by LukasKoenemann** [OpenModelica/OMPython#169]
### Description

I'm currently using ModelicaSystem via OMPython to optimize my modelica model using "Built-in Dynamic Optimization using Annotations". After calling the simulate function I get the simulation results correctly. Is it possible to fetch the information of the IPOPT solver (e.g. "No optimal solution found")?

Afterwards I would use the information in the postprocessing of the simulation.

### Steps to Reproduce

```
from OMPython import ModelicaSystem
model = ModelicaSystem(...)
result = model.simulate(...)
```

**Comment by LukasKoenemann** [comment]
Another possibility would be to read out the min/max values using the ModelicaSystem Object, but using `model.getQuantities(variable)` Funktion does not return the minimum or maximum value of the variable.

**Comment by arun3688** [comment]
@LukasKoenemann because we are not parsing those information, but i will implement that functionality to `getQuantities()` API to return min and max values

**Comment by LukasKoenemann** [comment]
@arun3688 Thanks! That would be great.

**Comment by arun3688** [comment]
@LukasKoenemann the functionality is implemented with this commit https://github.com/OpenModelica/OMPython/commit/6e626ed1632958ce7c97c588f122c7ca7a6a1d97

Now we get the following information from the API
```
>>> mod.getQuantities("x")
[{'name': 'x', 'changeable': 'true', 'description': None, 'variability': 'continuous', 'causality': 'local', 'alias': 'noAlias', 'aliasvariable': None, 'start': '1.0', 'min': '3.0', 'max': '4.0'}] 
```
if min and max attribute is not present then None is returned, Please pull the latest changes from master and test it

**Comment by LukasKoenemann** [comment]
That works fine for me. Thank you for the fast reply and solution!

**Comment by arun3688** [comment]
@LukasKoenemann I am closing this issue, please open new issue incase you face any problems
