### ISSUE TITLE
using ZeroMQ messaging instead of CORBA/omniORB?

### ISSUE THREAD

**Issue by pierre-haessig** [OpenModelica/OMPython#17]
Hi,

(This is more an open question rather than an issue.)

I was wondering if, in the mid term, there was the idea to replace the communication channel between the OMC and Python. I find the present choice (CORBA/omniORB) to be slightly complicated (*). To be clear, I have zero knowledge of these messaging systems. Only, I know people at IPython were very happy with ZMQ (which they started using when they split the kernel and the front end to make the Notebook interface). Also, Googling for "Corba ZMQ", I just found a link to a [2011 study by people from CERN](http://zeromq.wdfiles.com/local--files/intro%3Aread-the-manual/Middleware%20Trends%20and%20Market%20Leaders%202011.pdf). Of course the use case is different, but I just read through the paper and the story is they were looking for a replacement for their existing CORBA infrastructure. ZMQ appeared their best options (many criterions: simplicity, features...).

Now this is just an empty idea since I don't plan to start working on this, but maybe it is a useful suggestion?

best,
Pierre

(*)I mean simple practical issues: no pip install, no conda install. For Anaconda, I've found a third party built package at https://anaconda.org/mutirri/omniorb but after installation, I still get an `ImportError: No module named omniORB`...

**Comment by thorade** [comment]
For me the first results of a [Google search "Corba ZMQ"](https://www.google.com/search?q=corba+zmq) is this:
http://accelconf.web.cern.ch/AccelConf/ICALEPCS2013/papers/tucocb07.pdf

**Comment by dietmarw** [comment]
Given the ongoing struggles with getting omniORB running I totally support this idea.

**Comment by dietmarw** [comment]
@pierre-haessig 
> (*)I mean simple practical issues: no pip install, no conda install. For Anaconda, I've found a third party built package at https://anaconda.org/mutirri/omniorb but after installation, I still get an ImportError: No module 

The reason for this is that conda runs its python environment isolated from the system. I ran into the same problem and the only solution I found (as I could not figure out how to make conda system package aware) is to not us conda but the system python and pip.

**Comment by adeas31** [comment]
OMPython now has ZeroMQ. See #23.

**Comment by pierre-haessig** [comment]
Great. Thanks for this major improvement!
