### ISSUE TITLE
Mistyped default fileNamePrefix

### ISSUE THREAD

**Issue by JavierArroyoBastida** [OpenModelica/OMPython#176]
### Description
The check for the default `fileNamePrefix` is mistyped in the following line: 
https://github.com/OpenModelica/OMPython/blob/52e3dcd59fe283dcf8770297126672c22209853d/OMPython/__init__.py#L1596
which shows `"<default"` but should be `"<default>"`
This can lead to wrong paths eventually leading to problems when compiling the FMU. 
Simply adding the missing character `>` at the end of the string would fix the issue.

**Comment by casella** [comment]
@JavierArroyoBastida can you please make a pull request to fix it?

**Comment by JavierArroyoBastida** [comment]
Sure thing! here it is: https://github.com/OpenModelica/OMPython/pull/178.
