### ISSUE TITLE
unable to install OMPython using pip

### ISSUE THREAD

**Issue by Thirumalesh-HS** [OpenModelica/OMPython#2]
I am trying to install OMPython in Ubuntu using the command 

pip install git+git://github.com/OpenModelica/OMPython.git

I am getting the error message as:

Downloading/unpacking git+git://github.com/OpenModelica/OMPython.git
  Cloning git://github.com/OpenModelica/OMPython.git to /tmp/pip-nUtv8Z-build
fatal: unable to connect to github.com:
github.com[0: 192.30.252.131]: errno=Connection timed out

  Complete output from command /usr/bin/git clone -q git://github.com/OpenModelica/OMPython.git /tmp/pip-nUtv8Z-build:
  
----------------------------------------
Cleaning up...
Command /usr/bin/git clone -q git://github.com/OpenModelica/OMPython.git /tmp/pip-nUtv8Z-build failed with error code 128 in None
Storing debug log for failure in /tmp/tmpiA5yom

Please help me solve this issue

Thank you

**Comment by sjoelund** [comment]
Seems you could not connect to github, try again later.

**Comment by Thirumalesh-HS** [comment]
Thanks.

I tried with manual installation by running the command:
python setup.py install
I am getting this error.
Exception: Path not found: /usr/share/omc/omc_communication.idl

**Comment by sjoelund** [comment]
Where is your OpenModelica installation?

**Comment by Thirumalesh-HS** [comment]
Following is the path where OpenModelica got installed
/var/cache/apt/archives/openmodelica_25613-1_amd64.deb

**Comment by sjoelund** [comment]
You will have a better luck with the nightly builds (requires uninstalling the openmodelica packages and reinstalling the new ones with version number 1.9.3 which sorts lower than 25613). If you are using the release repository, you might also have an ompython deb package somewhere in there.

**Comment by Thirumalesh-HS** [comment]
Ok . I had installed the stable build. So is there a way to install OMPython in this build?

Thanks

**Comment by sjoelund** [comment]
apt-get install ompython should work

**Comment by Thirumalesh-HS** [comment]
Thank you. Got working OMPython now.
