### ISSUE TITLE
OMPython Installation Error

### ISSUE THREAD

**Issue by hchesser** [OpenModelica/OMPython#21]
Hello,
I am trying to install OMPython in Python 3.5 (Anaconda3) on a Windows 10 laptop.  

I have already built omniORB 4.2.1 from source using VS2015 and have installed OpenModelica1.9.4-dev.  The OPENMODELICAHOME environment variable is set to C:\OpenModelica1.9.4-dev.

I keep getting:

error: package directory 'OMPythonIDL' does not exist 

(but it does in the OpenModelica directory).  I even added the full path to OMPythonIDL to my path but I still get the same error.

One thing I am unsure of is the omniORBpy package - I see there is something available on sourceforge for.  Do I need this package before installing OMPython?

**Comment by arun3688** [comment]
We do not support OMPython in Python 3 , OMPython works only on Python 2 versions

**Comment by adeas31** [comment]
I wonder why you have installed OpenModelica1.9.4-dev? It is very old version.
Download OpenModelica1.11.0 and you don't need to build omniORB since we provide the pre-built binaries.

**Comment by hchesser** [comment]
I am trying to install the OM kernel for Jupyter Notebook - https://github.com/OpenModelica/jupyter-openmodelica
The installation requires that OPENMODELICAHOME be set as follows:
OPENMODELICAHOME=C:/OpenModelica1.9.4-dev/
So just installed that OM version.  I did notice OMPython came with this older version of OM as well.  When I tried running setup.py in that directory it didn't work either.

Anyway I can uninstall omniORB and try the 1.11.0 of OM.  But will it run with Python 3?

**Comment by arun3688** [comment]
Python 3 is not supported

**Comment by dietmarw** [comment]
The installation instructions as given by the current README do **not** work for Windows users. 

The problem is that one needs to execute the installation (pip or setup.py) from within `OpenModelica....\share\omc\scripts\PythonInterface\`. Only then you will be able to succeed. 

Also the readme should be changed to use the master.zip address and not git+ address (one less unnecessary dependency).

**Comment by adeas31** [comment]
I updated the instructions and removed the git dependency #26

**Comment by JanHELF** [comment]
Hi, ist Python 3. still not supported?
Or is there anything planned?

Cheers Jan

**Comment by dietmarw** [comment]
OMPython works fine with Python3 and ZMQ. Just have a look at the README

**Comment by thorade** [comment]
Python 3 works fine, and is already used by 75% of the users, according to download stats of the last 30 days:
```
pypinfo --percent ompython pyversion
```

| python_version | percent | download_count |
| -------------- | ------- | -------------- |
| 3.7            |  44.07% |             26 |
| 2.7            |  23.73% |             14 |
| 3.6            |  22.03% |             13 |
| 3.5            |   8.47% |              5 |
| 3.4            |   1.69% |              1 |
| Total          |         |             59 |

**Comment by JanHELF** [comment]
@dietmarw thank you for your answer.

I am using Python 3.7.0 and will install ZMQ 4.2.5., pyzmq v17.1.2 and libzmq.
On open question for me is: must be libzmq installed separately?

And is there anything else to consider for the installation? 

Cheers Jan

**Comment by dietmarw** [comment]
`pip` takes care of the dependencies.

**Comment by thorade** [comment]
pip takes care of all dependencies that are on PyPi, OMC still has to be installed seperately.

**Comment by sjoelund** [comment]
And if you want to use the CORBA stuff, you need omniidl-python installed prior to running the pip command... But with a modern OMC that's not necessary.

**Comment by Yulu76** [comment]
> I'm using python35 (anaconda3) and have installed ZMQ and pyzmq. However when I tried to use the command "ModelicaSystem" I got the following error message

  File "C:\Logiciels\anaconda3\envs\py35\lib\site-packages\OMPython\__init__.py", line 127, in _connect_to_omc
    from omniORB import CORBA

ImportError: cannot import name 'CORBA'

Import ModelicaSystem from OMPython was succed. And I understood that omniORB is not compatible with py35? So I installed and then unstalled omniORB. I don't understand why I get this error..

**Comment by JanHELF** [comment]
Thank you for your answers

Jan
