### ISSUE TITLE
ModelicaSystem does not Load Libraries before Model

### ISSUE THREAD

**Issue by jules-l-jimmy** [OpenModelica/OMPython#218]
On the latest OMPython, when using ModelicaSystem class with custom packages installed in custom directory and loading a model inside these packages, I have an error due to the fact that ModelicaSystem init loads the file and then the library.

To solve this, I exchanged the loadFile and loadLibrary in the `__init__.py` file line 862

Now it looks like this
```
        if fileName is not None:
            self.loadLibrary(verbose)
            self.loadFile(verbose)
```

**Comment by arun3688** [comment]
@jules-l-jimmy can you open a PR with the changes you made

**Comment by jules-l-jimmy** [comment]
@arun3688 Will you do a release with the fix soon ?

Best
