### ISSUE TITLE
Proposal: update ModelicaSystem to use logger & exceptions

### ISSUE THREAD

**Issue by syntron** [OpenModelica/OMPython#227]
I have some code changes which replace all print statements in ModelicaSystem with calls to the python logging infrastructure. Furthermore, it uses Exceptions if usefull.

If there is some interest, I could post it for review / prepare a pull request ...

**Comment by adeas31** [comment]
Sounds good!

**Comment by syntron** [comment]
please see #228 for data / the pull request

**Comment by syntron** [comment]
merged => close it
