### ISSUE TITLE
pylint

### ISSUE THREAD

**Issue by thorade** [OpenModelica/OMPython#39]
As mentioned by @dietmarw in #1 you should run a code analysis with [pylint ](https://www.pylint.org/)or some other tool.
If you happen to use Spyder as your editor, this can be done (for the currently active file) by just pressing F8.
At least the errors should be fixed (or looked at), some of them are due to Py2 vs Py3, some of them are due to omniORB not being installed on my Windows machine, but some are real errors that need a fix.

![spyder_codeanalysis](https://user-images.githubusercontent.com/314571/27372562-5b4eed0a-5665-11e7-8795-8fba1988fd85.png)

**Comment by thorade** [comment]
@adeas31 Which one of the two getPackages functions is correct?
https://github.com/OpenModelica/OMPython/blob/master/OMPython/__init__.py#L264-L268
One of the two should be removed.

**Comment by adeas31** [comment]
Actually both are correct but we can merge them as one,
```
def getPackages(self, className="AllLoadedClasses"):
        return self.ask('getPackages', className)
```

Will you make a PR?

**Comment by thorade** [comment]
pylint reports a couple of time:
E1101: ex has no 'message' member
https://stackoverflow.com/a/33239954/874701

**Comment by thorade** [comment]
Closing for now, would be good to re-run the test on a regular basis.
