### ISSUE TITLE
Installing via pip causes error omnipy version error

### ISSUE THREAD

**Issue by RexFuzzle** [OpenModelica/OMPython#4]
Good Afternoon.

It seems that when the package is installed via pip on OSX an error occurs as PMPythonIDL sends version 3 and omnipy needs version 4.2. 
The issue is resolved when installing OMPython using the command on the github README page.
I have replicated the issue on 3 computers running OSX.
Both github and pypi have version 2.0.2 for OMPython

**Comment by sjoelund** [comment]
So it works when using `python setup.py install` but not when using `pip` is what you are saying?

OMPythonIDL is not part of the sources, but is automatically generated by the omniidl version installed on the system.

Do these machines have multiple python versions installed (macports, etc)?

**Comment by RexFuzzle** [comment]
No, it doesn't work when installing with `pip install OMPython` , but does work if I install it using 
` pip install git+git://github.com/OpenModelica/OMPython.git `
No, single version of python installed with brew. Haven't looked at it in too much detail but it would seems that pypi changes something.

**Comment by sjoelund** [comment]
If you have a version of Python inside brew, you have more than 1 python installed since OSX comes with its own Python. And this might mean you also have different pip versions.

Version 2.0.2 is a bit older though. Are there still problems with 2.0.5 and 2.0.6?

**Comment by sjoelund** [comment]
Oh, now I see it. The source distribution does run the omniidl command because it's not present on some installations of omniorb... So the uploaded version to pypi does have OMPythonIDL generated by my system, which might not be compatible with another system...

I'll try to change it to always try to run omniidl, but fall back to the generated file if the commands fail.

**Comment by sjoelund** [comment]
pip should now work with 2.0.7 (I hope)

**Comment by RexFuzzle** [comment]
Perfect- it is working now- thank you
