### ISSUE TITLE
typeCheck on python3 - type long does not exist

### ISSUE THREAD

**Issue by forgi86** [OpenModelica/OMPython#47]
the function typeCheck defined at line 55 of __init__.py of OMParser uses the type long in the list 
types. This type does not exist any more in python 3 and thus I get an error when I try to instantiate
an object of ModelicaSystem. I had to remove long from the list and now it works.

**Comment by bilderbuchi** [comment]
Is that line still there in current master?

**Comment by forgi86** [comment]
It is still there at line 55 of __init__.py

**Comment by thorade** [comment]
@forgi86 Have you seen #1 and #46 ?

**Comment by adeas31** [comment]
This is fixed in #46
