### ISSUE TITLE
Potential error in OMPython documentation OMCSession() vs. OMCSessionZMQ()

### ISSUE THREAD

**Issue by GeorgFerdinandSchneider** [OpenModelica/OMPython#48]
Hello!

I have found a potential error in the html documentation of OMPython:

In the online documentation [online](https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/ompython.html) as first example

**To get started, create an OMCSessionZMQ object:**

>>> from OMPython import OMCSessionZMQ
>>> omc = OMCSessionZMQ()**

is given.

However, from reading the help() it should be

**To get started, create an OMCSession object:**

>>> from OMPython import OMCSession
>>> omc = OMCSession()

Unfortunately I did not find the source of the website in this github repos for correcting myself.

Best

**Comment by thorade** [comment]
The documentation is generated from this repo:
https://github.com/OpenModelica/OpenModelica-doc

**Comment by thorade** [comment]
OMPython supports two session types, Corba session or ZMQ session. 
ZMQ was introduced with #23. 
So both commands should work, the first one starts a ZMQ session, the second one starts a Corba session. 

Probably the documentation should be updated to either mention both session types, or to use the preferred session type in all help&doc texts.

**Comment by adeas31** [comment]
The documentation and help both mentions the OMCSession and OMCSessionZMQ and the ways on how to use them.
