### ISSUE TITLE
tags and releases and PyPI

### ISSUE THREAD

**Issue by thorade** [OpenModelica/OMPython#52]
Other OpenModelica repositories use tags and realeases and it would be nice to also at least **tag** the commits that get packaged with the official full OpenModelica release.
That OMPython version should then also be uploaded to PyPI.
https://pypi.python.org/pypi/OMPython
@sjoelund you are marked as package owner

**Comment by sjoelund** [comment]
I now tagged v3.0.0 and uploaded it to pypi

**Comment by thorade** [comment]
Thanks.
