### ISSUE TITLE
 OMPython - ERROR - OMC Server is down 

### ISSUE THREAD

**Issue by kingaj12** [OpenModelica/OMPython#60]
Hi - I am updating the Docker image from the [jupyter-openmodelica project](https://github.com/OpenModelica/jupyter-openmodelica).  I can open a notebook with the OpenModelica kernel but then it crashes with the above error message.  The thread [#1](https://github.com/OpenModelica/OMPython/issues/1) seems to go into some of the issues.

Here is the Docker file

    # Get a minimal notebook from the public Docker jupyter images
    FROM jupyter/minimal-notebook
    # Switch to root to install new components
    USER root
    # Update index
    RUN apt-get update
    # Install minimal OpenModelica Components from the nightly build
    RUN for deb in deb deb-src; do echo "$deb http://build.openmodelica.org/apt xenial nightly"; done | sudo tee /etc/apt/sources.list.d/openmodelica.list
    RUN wget -q http://build.openmodelica.org/apt/openmodelica.asc -O- | sudo apt-key add -
    RUN apt-key fingerprint
    RUN apt-get update
    RUN apt-get install -y openmodelica
    # Switch back to jupyter notebook default user to install the OpenModelica kernel
    USER $NB_UID
    # Install OMPython and jupyter-openmodelica kernel
    RUN pip install -U git+git://github.com/OpenModelica/OMPython.git
    RUN pip install -U git+git://github.com/OpenModelica/jupyter-openmodelica.git

I build and run this using the following commands (where jupyter-openmodelica/ is the directory containing the Dockerfile)
  
    docker build -t openmodelica jupyter-openmodelica/
    docker run -p 8888:8888 openmodelica

Here is the output when I open the notebook from the jupyter-openmodelica project :

    2018-03-08 17:27:20,256 - OMPython - ERROR - OMC Server is down. Please start it! Log-file says:
    Created ZeroMQ Server.
    Dumped server port in file: /tmp/openmodelica.nobody.port.cd065c756553460fb78c4bb0d3fb8771    Traceback (most recent call last):
      File "/opt/conda/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
      File "/opt/conda/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
      File "/opt/conda/lib/python3.6/site-packages/openmodelica_kernel/__main__.py", line 43, in <module>
    IPKernelApp.launch_instance(kernel_class=OpenModelicaKernel)
      File "/opt/conda/lib/python3.6/site-packages/traitlets/config/application.py", line 657, in launch_instance
    app.initialize(argv)
      File "<decorator-gen-123>", line 2, in initialize
      File "/opt/conda/lib/python3.6/site-packages/traitlets/config/application.py", line 87, in catch_config_error
    return method(app, *args, **kwargs)
      File "/opt/conda/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 465, in initialize
    self.init_kernel()
      File "/opt/conda/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 376, in init_kernel
    user_ns=self.user_ns,
      File "/opt/conda/lib/python3.6/site-packages/traitlets/config/configurable.py", line 412, in instance
    inst = cls(*args, **kwargs)
      File "/opt/conda/lib/python3.6/site-packages/openmodelica_kernel/kernel.py", line 125, in __init__
    self.omc=OMCSessionZMQ()
      File "/opt/conda/lib/python3.6/site-packages/OMPython/__init__.py", line 502, in __init__
    self._connect_to_omc(timeout)
      File "/opt/conda/lib/python3.6/site-packages/OMPython/__init__.py", line 528, in _connect_to_omc
    raise Exception
    Exception

I hope there is some bandwidth on your part to look into this.  Once the Dockerfile is working I will contribute it to the jupyter- openmodelica project.

**Comment by arun3688** [comment]
Can you check your "OPENMODELICAHOME" in your environmental variable, if you have older version of openmodelica, download the latest nightly builds and check whether OMPython is working

**Comment by kingaj12** [comment]
What should OPENMODELICAHOME be after `apt-get install -y openmodelica` ?

**Comment by arun3688** [comment]
if you are running on Linux then no need to set OPENMODELICAHOME

**Comment by kingaj12** [comment]
The Docker build downloads the openmodelica release for Ubuntu 16.04 Xenial:

    RUN for deb in deb deb-src; do echo "$deb http://build.openmodelica.org/apt xenial release"; done | sudo tee /etc/apt/sources.list.d/openmodelica.list

**Comment by arun3688** [comment]
I hope that should work fine

**Comment by kingaj12** [comment]
:( no joy.  Same error.

**Comment by arun3688** [comment]
i can see your docker image running from base image  jupyter/minimal-notebook and i think they have conda environment for python, i am not sure about that may be you can try with the existing dockerfile and try and see and before that try to check whether omc is working inside the docker container 
try to run docker run -p 8888:8888 openmodelica bash 
and check whether omc is working by typing omc

**Comment by kingaj12** [comment]
I'm not sure I'm doing it right, but this is what I get

    $ docker run -p 8888:8888 jupyter-openmodelica "/usr/bin/bash cmd"
    [FATAL tini (6)] Executing child process 'C:/Program Files/Git/usr/bin/bash cmd' failed: 'No such file or directory'

**Comment by kingaj12** [comment]
Ah!  I found something

    $ docker run -p 8881:8888 jupyter-openmodelica start.sh "ls -l /usr/bin/omc"
    Container must be run with group root to update passwd file
    Executing the command: ls -l /usr/bin/omc
    -rwxr-xr-x 1 root root 6192 Oct 26 08:10 /usr/bin/omc

**Comment by kingaj12** [comment]
It works!!!!  Have to run it as root:

     docker run -p 8888:8888 --user root jupyter-openmodelica
