### ISSUE TITLE
Third argument of "ModelicaSystem" not documented

### ISSUE THREAD

**Issue by dietmarw** [OpenModelica/OMPython#63]
When trying to use the `ModelicaSystem` 
 function as documented in the [User's Guide](https://www.openmodelica.org/doc/OpenModelicaUsersGuide/latest/ompython.html#enhanced-ompython-features) it simply does not tell you what the quite central **third** argument should look like. 

It took a lot of searching and going through the code to finally figure that it expects the to be used library name as a string. 

E.g., 
```mo
mod=ModelicaSystem("BouncingBall.mo","BouncingBall","Modelica")
```

Also I'm not sure how to specify the dependency from several libraries.

**Comment by adeas31** [comment]
I agree that this should be documented and should be improved to allow several libraries.
However, if #64 is fixed then perhaps we can just simple remove this argument?

**Comment by dietmarw** [comment]
Yes I agree, if #64 works then we do not need this. This would really be the best solution. So depending on how long that would take then the documentation fix should still be considered.

**Comment by adeas31** [comment]
I updated the `ModelicaSystem` to accept a list of dependent libraries and also documented this in the users guide.
