### ISSUE TITLE
unable to import OMCSessionZMQ

### ISSUE THREAD

**Issue by Yulu76** [OpenModelica/OMPython#78]
I've tried to run a simple test on Spyder but it doesn't work: 
>>> from OMPython import OMCSessionZMQ
I got the error: ImportError: cannot import name 'OMCSessionZMQ'

For information, I've installed OMPython with the command below in the enviroment of Anaconda (py35):  
>>>cd %OPENMODELICAHOME%\share\omc\scripts\PythonInterface
>>>python -m pip install . 

And my OM version is 1.11.0. 

Thanks a lot for your help!

**Comment by adeas31** [comment]
`ZeroMQ` is introduced in 1.12. You need to update your OpenModelica.

**Comment by Yulu76** [comment]
> `ZeroMQ` is introduced in 1.12. You need to update your OpenModelica.

Is there a way to stay in 1.11 and use OMPython? Because the model I've received doen't simulate on 1.12 but only on 1.11. Thanks for your help.

**Comment by sjoelund** [comment]
`from OMPython import OMCSession` uses the older CORBA interface

**Comment by Yulu76** [comment]
> `from OMPython import OMCSession` uses the older CORBA interface

When I do 
> from OMPython import OMCSession
> omc = OMCSession()

I get this error : 
ImportError: cannot import name 'CORBA'

Is CORBA supported by Python3? I'm using python3.5

**Comment by sjoelund** [comment]
It is, but you need to have installed omniidl and Python support for CORBA prior to running the pip install command so that it will generate the necessary files. This is quite easy to do on Linux, but is quite painful on Windows...

**Comment by Yulu76** [comment]
> It is, but you need to have installed omniidl and Python support for CORBA prior to running the pip install command so that it will generate the necessary files. This is quite easy to do on Linux, but is quite painful on Windows...

So to recap, I'm using OM 1.11 (due to model restriction) and python 3.5 (anaconda) on Windows. I try to use OMPython to run several simulations with different parameter values. What would be the best option to install OMPython in your opinion? 
Is there a tutoriel to install omniidl on Windows? Because passing to OM 1.12 is currently not an option for me.  
Would it be easier if I go through FMU?

**Comment by Yulu76** [comment]
I removed OM v1.11 and installed v1.12. When I do  
>> from OMPython import OMCSessionZMQ
I still get this error: AttributeError: module 'OMPython' has no attribute 'OMCSessionZMQ'

I think the problem might not be related to the version of OpenModelica but something else. Have you had this error before?

**Comment by adeas31** [comment]
Did you run `pip install` after installing v1.12?
What is the output of `python -m pip install .`? Maybe it has failed and python is still using the old OMPython.

**Comment by Yulu76** [comment]
I've just found the solution: after install OM v1.12 and OMPython, I had to install manuelly pyzmq in the repertory of PythonInterface using >> pip install pyzmq.
Now I can import successfully OMCSessionZMQ! 

BUT an exception is raised when I do >> omc = OMCSessionZMQ( )    
I got this error: 
"OMC Server is down. Please start it! Log-file says: Le chemin d'accŠs sp‚cifi‚ est introuvable." 
The exception is from  
File "C:\Logiciels\anaconda3\envs\py35\lib\site-packages\OMPython\__init__.py", line 528, in _connect_to_omc
    raise Exception

**Comment by thorade** [comment]
Something is wrong. pip should have handled all dependencies, no need to install pyzmq manually.
Can you please rerun the following commands?
Either run 
```
python -m pip install -U https://github.com/OpenModelica/OMPython/archive/master.zip
```
or run
```
cd %OPENMODELICAHOME%\share\omc\scripts\PythonInterface
python -m pip install -U .
```

**Comment by Yulu76** [comment]
So I just ran 

```
cd %OPENMODELICAHOME%\share\omc\scripts\PythonInterface
python -m pip install -U .

```
and 

`from OMPython import OMCSessionZMQ`

This worked. But when I call OMCSessionZMQ() I still got the same exception raised: 

`2018-11-22 13:53:22,700 - OMPython - ERROR - OMC Server is down. Please start it! Log-file says:
Le chemin d'accŠs sp‚cifi‚ est introuvable.

Traceback (most recent call last):

  File "<ipython-input-23-836171fe76d5>", line 1, in <module>
    omc = OMPython.OMCSessionZMQ()

  File "C:\Logiciels\anaconda3\envs\py35\lib\site-packages\OMPython\__init__.py", line 502, in __init__
    self._connect_to_omc()

  File "C:\Logiciels\anaconda3\envs\py35\lib\site-packages\OMPython\__init__.py", line 528, in _connect_to_omc
    raise Exception

Exception`

**Comment by thorade** [comment]
What does OpenModelicaHome point to?
And what is the output of `pip show ompython`?

**Comment by Yulu76** [comment]
and there's an slight error in the README.txt of OMPython, that was why the install didn't work for me in the first place: 

```
cd %OPENMODELICAHOME%\share\omc\scripts\PythonInterface
python -m pip install .
```

But instead it should be: 
```
python -m pip install -U .
```

**Comment by Yulu76** [comment]
OpenModelicaHome points to **None** when I run `print (os.environ.get("OpenModelicaHome"))`

So there's something wrong. 

`pip show ompython` gives the following output: 

> Name: OMPython
> Version: 3.0.0
> Summary: OpenModelica-Python API Interface
> Home-page: http://openmodelica.org/
> Author: Adeel Asghar
> Author-email: adeel.asghar@liu.se
> License: BSD, OSMC-PL 1.2, GPL (user's choice)
> Location: c:\logiciels\anaconda3\envs\py35\lib\site-packages
> Requires: future, pyzmq, numpy, pyparsing
> Required-by:

**Comment by Yulu76** [comment]
I just saw this in the __init__.py : 

```
def _get_omc_path(self):
        try:
            self.omhome = os.environ.get('OPENMODELICAHOME')
            if self.omhome is None:
                self.omhome = os.path.split(os.path.split(os.path.realpath(spawn.find_executable("omc")))[0])[0]
```

But when I run `print (os.path.split(os.path.split(os.path.realpath(spawn.find_executable("omc")))[0])[0])`
I got this in return: 

> NameError: name 'spawn' is not defined

**Comment by thorade** [comment]
On Windows, it might be required to restart, or log off and log on, to make sure env variables are set after installing software.
Can you try and restart, then check the variable, CD into correct for, run out install command again, post output of pip show ompython

**Comment by thorade** [comment]
Sorry, maybe the env variable name has to be all capital letters. In any way, it must not be empty, otherwise all other commands will not work as expected. Also, I do not know what the command `cd %OPENMODELICAHOME%\share\omc\scripts\PythonInterface` did for you if that variable was empty?

**Comment by Yulu76** [comment]
I restart Windows and now the command `omc = OMCSessionZMQ()` works ! 

Thanks a lot for your help :)))
