### ISSUE TITLE
Error during linearization

### ISSUE THREAD

**Issue by gitlyap** [OpenModelica/OMPython#88]
Hello,

Infos:
System: Archlinux
OMCompiler v1.13.2 AND v1.14.0-dev.257+g5daaf9ba0
OMPython: 3.1.2 (with pip installed)

if I want to linearize a model, I get the following error message:
```
~/.local/lib/python3.7/site-packages/OMPython/__init__.py in __getMatrix(self, xParameter, sizeParameter)
   1789         xElemNames.sort(key=len)
   1790         sortedX = xElemNames
-> 1791         size_ = int(self.getParameters(sizeParameter))
   1792         matX = []
   1793         matX = [[] for i in range(size_)]

TypeError: int() argument must be a string, a bytes-like object or a number, not 'tuple'
```
I use the Infos from here: https://openmodelica.org/doc/OpenModelicaUsersGuide/latest/ompython.html#usage-of-linearization-methods:
```
from OMPython import OMCSessionZMQ 
omc = OMCSessionZMQ() 
model_path=omc.sendExpression("getInstallationDirectoryPath()") + "/share/doc/omc/testmodels/" 
from OMPython import ModelicaSystem
mod=ModelicaSystem(model_path + "VanDerPol.mo", "VanDerPol")
mod.linearize()
```
with "VanDerPol", "BouncingBall" and an own small electric example with one real input and one real output.

what is my fault in linearizing the model?

Thanks for your help.

**Comment by arun3688** [comment]
@gitlyap  The error is fixed with this commit https://github.com/OpenModelica/OMPython/commit/aef01968aa75aa6f443b6feec4c868a8b534ec6e, check it whether it works

**Comment by gitlyap** [comment]
@arun3688 perfect, it works. Thanks.
