### ISSUE TITLE
getParameters/__getXXXs fails when called single multicharacter argument

### ISSUE THREAD

**Issue by pierre-haessig** [OpenModelica/OMPython#96]
Dear OMPython maintainers,

Using OMPython 3.1.2 and OpenModelica 1.13.2, I think there is a bug when calling `getParameters` (and the underlying function `__getXXXs`, so that other getX functions may be affected) with a single parameter name which has several characters. Here is an example with the test model dcmotor:

```python
from OMPython import OMCSessionZMQ

omc = OMCSessionZMQ()
model_path=omc.sendExpression("getInstallationDirectoryPath()") + "/share/doc/omc/testmodels/"

from OMPython import ModelicaSystem
mod=ModelicaSystem(model_path + "dcmotor.mo","dcmotor")
```

when calling `mod.getParameters('load.J')`, one gets the error message `'l' is not in list`, meaning that the 'load.J' string is wrongly interpreted like ['l', 'o', 'a' ...]. 

I believe the issue comes from iteration in the elements of `names` in the case `elif len(names)==1` in [__getXXXs](https://github.com/OpenModelica/OMPython/blob/master/OMPython/__init__.py#L1237). Maybe the goal was to get many one-letter params at once? Anyway, this breaks the function.

 A solution could be remove the special case `elif len(names)==1` and expand `elif len(names) > 1:` into `else` (implicitely >=1).

Final thought: I believe the two  lines `except ValueError as e: print(e)` shoud be removed since they complicate debugging.

**Comment by arun3688** [comment]
@pierre-haessig This is fixed with this commit https://github.com/OpenModelica/OMPython/commit/2cc25e3d5f3363ae3638027ecca5eb2f3f721f37,

**Comment by pierre-haessig** [comment]
Great! In the coming weeks, it's not sure I'll work with OMPython, but I'll give it a try. Let's close the issue for now and I or somebody else will reopen it if needed, what do you think?

**Comment by arun3688** [comment]
@pierre-haessig , I will close this issue as of now
