### ISSUE TITLE
setSimulationOptions startTime and stopTime values are sometimes ignored

### ISSUE THREAD

**Issue by alidaf** [OpenModelica/OMPython#97]
I'm trying to do a restart simulation based on the bouncing ball, i.e. I want to end the initial run early, grab the final values of height and velocity and use those as inputs to a continuation run. It works apart from being able to consistently set the start time and end time of the continuation run. 

I use setSimulationOptions 3 times. The first to set the start and end times of the initial run, e.g. startTime = 0, stopTime = 2.
The second define the continuation run, e.g.
startTime = 2, stopTime = 7.
I then do a third run that runs all the way through for comparison, e.g.
startTime = 0, stopTime = 7.

What happens is that the options are sometimes set and other times not. It is apparently random.

**Comment by arun3688** [comment]
@alidaf , This issue is fixed with this commit https://github.com/OpenModelica/OMPython/commit/2cc25e3d5f3363ae3638027ecca5eb2f3f721f37, Test it

**Comment by alidaf** [comment]
It appears to be consistent now thank you.
